# Generated by Django 3.1.3 on 2021-12-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_studentpageform_description2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpageform',
            name='description2',
            field=models.TextField(default='Второй абзац', max_length=255),
        ),
    ]
