# Generated by Django 3.1.3 on 2021-12-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_studentpageform_description2'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpageform',
            name='title',
            field=models.CharField(default='Example', max_length=20),
        ),
    ]
