# Generated by Django 3.1.3 on 2021-12-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_studentpageform_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpageform',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentpageform',
            name='video_descriptions',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='talapkerpagetable',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
