# Generated by Django 3.1.3 on 2021-12-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_studentpageform_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpageform',
            name='description_second',
            field=models.TextField(default='', max_length=255),
        ),
    ]
