# Generated by Django 3.1.3 on 2021-12-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_studentpageform_description_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='navlist',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentpageform',
            name='description',
            field=models.TextField(max_length=255, verbose_name=' Первый абзац'),
        ),
        migrations.AlterField(
            model_name='studentpageform',
            name='description_second',
            field=models.TextField(default='', max_length=255, verbose_name=' Второй абзац'),
        ),
    ]
