# Generated by Django 3.1.3 on 2021-12-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20211217_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='navlist',
            name='description_second',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='navlist',
            name='description',
            field=models.TextField(default='', max_length=600),
        ),
    ]
