# Generated by Django 3.1.3 on 2021-12-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20211217_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='navlist',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
