# Generated by Django 3.1.3 on 2021-12-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20211217_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspostform',
            name='slug',
            field=models.SlugField(),
        ),
    ]
