# Generated by Django 3.1.3 on 2021-12-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20211217_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspostform',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
