# Generated by Django 3.1.3 on 2021-12-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20211217_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspostform',
            name='slug',
        ),
        migrations.AlterField(
            model_name='navlist',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
