# Generated by Django 3.1.3 on 2021-12-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20211217_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspostform',
            name='slug',
            field=models.SlugField(default='', max_length=20),
        ),
    ]
