# Generated by Django 3.1.3 on 2021-12-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_newspostform_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navlist',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='newspostform',
            name='slug',
            field=models.SlugField(default='', max_length=20, unique=True),
        ),
    ]
