# Generated by Django 3.1.3 on 2021-12-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_auto_20211217_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navlist',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='newspostform',
            name='slug',
            field=models.SlugField(default='', max_length=20),
        ),
    ]
