# Generated by Django 3.1.3 on 2021-12-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_auto_20211217_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspostform',
            name='slug',
        ),
    ]
