# Generated by Django 3.1.3 on 2021-12-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_auto_20211217_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
