# Generated by Django 3.1.3 on 2021-12-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_auto_20211217_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsbigpost',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='newslongpost',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='newsshortpost',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='talapkerpost',
            name='slug',
        ),
        migrations.AlterField(
            model_name='navlist',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
