# Generated by Django 3.1.3 on 2021-12-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_remove_gallery_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='newspostform',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
