# Generated by Django 3.1.3 on 2021-12-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_auto_20211224_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='students_life_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='students_life_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='gallery')),
            ],
        ),
        migrations.DeleteModel(
            name='students_life',
        ),
    ]
