# Generated by Django 3.1.3 on 2021-12-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_auto_20211227_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='for_parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='talapkerpagetable',
            name='table_description',
            field=models.TextField(max_length=100, verbose_name='Мамандык туралы'),
        ),
        migrations.AlterField(
            model_name='talapkerpagetable',
            name='table_description2',
            field=models.TextField(default='', max_length=100, verbose_name='Біліктілік туралы'),
        ),
    ]
