# Generated by Django 3.1.3 on 2021-12-27 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_auto_20211227_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='clubs_page_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='Основной плеер страницы')),
            ],
        ),
        migrations.RemoveField(
            model_name='clubs_page_form',
            name='video',
        ),
    ]
