# Generated by Django 3.1.3 on 2021-12-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0044_auto_20211229_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspostform',
            old_name='descriptionEN',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='newspostform',
            name='descriptionKZ',
        ),
        migrations.RemoveField(
            model_name='newspostform',
            name='descriptionRU',
        ),
        migrations.AddField(
            model_name='newspostform',
            name='description_en',
            field=models.TextField(default='', max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='newspostform',
            name='description_kk',
            field=models.TextField(default='', max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='newspostform',
            name='description_ru',
            field=models.TextField(default='', max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='newspostform',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newspostform',
            name='title_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newspostform',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
