# Generated by Django 3.1.3 on 2021-12-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_auto_20211229_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='swiperimg',
            name='description',
            field=models.TextField(default='', max_length=150),
        ),
    ]
