# Generated by Django 3.1.3 on 2021-12-31 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0046_swiperimg_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navlist',
            name='descriptionEN',
        ),
        migrations.RemoveField(
            model_name='navlist',
            name='descriptionKZ',
        ),
        migrations.RemoveField(
            model_name='navlist',
            name='descriptionRU',
        ),
        migrations.AddField(
            model_name='navlist',
            name='description',
            field=models.TextField(default='', max_length=800, verbose_name=' Первый абзац '),
        ),
        migrations.AddField(
            model_name='swiperimg',
            name='video',
            field=models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
