# Generated by Django 3.1.3 on 2021-12-31 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0047_auto_20211231_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwiperVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
            ],
        ),
        migrations.RemoveField(
            model_name='swiperimg',
            name='video',
        ),
    ]
