# Generated by Django 3.1.3 on 2021-12-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0048_auto_20211231_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiperimg',
            name='description',
            field=models.TextField(default='', max_length=100),
        ),
    ]
