# Generated by Django 3.1.3 on 2023-03-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0050_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='place',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='room',
            field=models.CharField(default='default_room_value', max_length=50),
        ),
    ]
