# Generated by Django 3.1.3 on 2023-03-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0051_auto_20230309_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='place',
            field=models.IntegerField(default=''),
        ),
    ]
