# Generated by Django 3.1.3 on 2023-03-09 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0052_auto_20230309_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='place',
        ),
        migrations.RemoveField(
            model_name='student',
            name='room',
        ),
    ]
