# Generated by Django 3.1.3 on 2023-03-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0054_auto_20230309_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='room',
        ),
    ]
