# Generated by Django 3.1.3 on 2023-03-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0055_remove_student_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubimage',
            name='club',
        ),
        migrations.DeleteModel(
            name='clubs_page_video',
        ),
        migrations.DeleteModel(
            name='for_parents',
        ),
        migrations.DeleteModel(
            name='NewsBigPost',
        ),
        migrations.DeleteModel(
            name='NewsLongPost',
        ),
        migrations.DeleteModel(
            name='NewsPostForm',
        ),
        migrations.DeleteModel(
            name='NewsShortPost',
        ),
        migrations.DeleteModel(
            name='StudentPageForm',
        ),
        migrations.DeleteModel(
            name='students_life_description',
        ),
        migrations.DeleteModel(
            name='students_life_img',
        ),
        migrations.DeleteModel(
            name='TalapkerPageTable',
        ),
        migrations.DeleteModel(
            name='TalapkerPost',
        ),
        migrations.DeleteModel(
            name='ValounterVideo',
        ),
        migrations.DeleteModel(
            name='clubImage',
        ),
        migrations.DeleteModel(
            name='clubs_page_form',
        ),
    ]
